### ISSUE TITLE
SimpleITK fails to build on 10.10.4

### ISSUE THREAD

**Issue by dmitrievk** [Homebrew/homebrew-science#2627]
==> Installing simpleitk from homebrew/homebrew-science
==> Downloading https://downloads.sourceforge.net/project/simpleitk/SimpleITK/0.
Already downloaded: /Library/Caches/Homebrew/simpleitk-0.8.0.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_
==> make install
/tmp/simpleitk20150806-1887-1o2mse/SimpleITK-0.8.0/Code/BasicFilters/include/sitkWhiteTopHatImageFilter.h:148: Error: Line indented less than expected (line 4 of pythoncode)
make[2]: *** [Wrapping/SimpleITKPYTHON_wrap.cxx] Error 229
make[2]: *** Deleting file `Wrapping/SimpleITKPYTHON_wrap.cxx'
make[1]: *** [Wrapping/CMakeFiles/SimpleITK_PYTHON.dir/all] Error 2
make: *** [all] Error 2
