### ISSUE TITLE
lightstringgraph fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2544]
```
==> Installing lightstringgraph from homebrew/homebrew-science
==> Downloading https://github.com/AlgoLab/LightStringGraph/archive/v0.1.0.tar.gz
==> Downloading from https://codeload.github.com/AlgoLab/LightStringGraph/tar.gz/v0.1.0
######################################################################## 100,0%
==> make
src/lsg/lsg.cpp:108:41: error: variable length array of non-POD element type 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
        stringstream convert(string(argv[++i]));
                                        ^
3 errors generated.
make: *** [obj/lsg/lsg.o] Error 1
```

Logs: https://gist.github.com/456a24a0425607d72753
