### ISSUE TITLE
Infernal 1.1.1 - Make Error 2 with fresh install of Linuxbrew

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#1931]
Got this unexpected error on _Red Hat Enterprise Linux Server release 7.1 (Maipo)_

```
==> Installing prokka dependency: infernal
==> Downloading http://selab.janelia.org/software/infernal/infernal-1.1.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/linuxbrew/Cellar/infernal/1.1.1
==> make
make[2]: *** [hmmpgmd] Error 1
make[2]: Leaving directory `/tmp/infernal-Vq2IGg/infernal-1.1.1/hmmer/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/infernal-Vq2IGg/infernal-1.1.1/hmmer'
make: *** [all] Error 2
```

**Comment by saketkc** [comment]
Can you `brew gist-logs infernal`?

**Comment by tseemann** [comment]
@saketkc Here you go!

```
% brew gist-logs infernal
Error: HTTP 403 Forbidden (expected 201)
```

**Comment by saketkc** [comment]
`brew install infernal -v` would do as well.

**Comment by tseemann** [comment]
I've made a API key now, the 403 was because I exceeded my limit.

Here is the log: https://gist.github.com/f0c981467aaf14e6fdd6

And thanks for the ```-v``` tip.

**Comment by saketkc** [comment]
This looks tricky. It builds fine on my Ubuntu 14.04 with `gcc4.9`.
@sjackman might help

**Comment by sjackman** [comment]
https://gist.github.com/tseemann/f0c981467aaf14e6fdd6#file-02-make-L239-L257

```
     GEN makenhmmerdb
exactmatch.o: In function `getFMHits':
exactmatch.c:(.text+0x12b): undefined reference to `fm_getChar'
exactmatch.c:(.text+0x144): undefined reference to `fm_getOccCount'
exactmatch.o: In function `main':
exactmatch.c:(.text.startup+0x3e2): undefined reference to `fm_configAlloc'
exactmatch.c:(.text.startup+0x40c): undefined reference to `fm_readFMmeta'
exactmatch.c:(.text.startup+0x4c4): undefined reference to `fm_readFM'
exactmatch.c:(.text.startup+0x4d7): undefined reference to `fm_readFM'
exactmatch.c:(.text.startup+0x726): undefined reference to `fm_initConfig'
exactmatch.c:(.text.startup+0x730): undefined reference to `fm_createAlphabet'
exactmatch.c:(.text.startup+0x850): undefined reference to `fm_getSARangeForward'
exactmatch.c:(.text.startup+0x99a): undefined reference to `fm_getSARangeReverse'
exactmatch.c:(.text.startup+0xa8e): undefined reference to `fm_getOriginalPosition'
exactmatch.c:(.text.startup+0xc2a): undefined reference to `fm_freeFM'
exactmatch.c:(.text.startup+0xc3a): undefined reference to `fm_freeFM'
exactmatch.c:(.text.startup+0xc9a): undefined reference to `fm_destroyConfig'
collect2: error: ld returned 1 exit status
make[2]: *** [exactmatch] Error 1
```

**Comment by sjackman** [comment]
Hi, Torsten. You have into install infernal before hmmer. Infernal includes an incompatible version of hmmer. See https://github.com/sjackman/docker-bio/blob/master/prokka/Dockerfile#L10-L12

```
# Install infernal before hmmer to avoid this error:
# exactmatch.c: undefined reference to `fm_getChar'
RUN brew install infernal -v
```

Or
```
brew unlink hmmer
brew install infernal
brew link hmmer
```

**Comment by jrherr** [comment]
Thank you all!  This thread helped me today!

**Comment by sjackman** [comment]
I'm glad it helped. I'm wondering if installing the `libhmmer.a` library may cause more trouble than it's worth. I think that any software that uses `libhmmer` is likely to include their own copy, like `infernal` which is what caused this trouble in the first place.

**Comment by tseemann** [comment]
I don't think I've ever come across any software that uses ```libhmmer``` except in the bundled case like you describe.

If we can solve this problem by ditching ```libhmmer.a``` I would welcome it!
