### ISSUE TITLE
Paraview 5.2 fails to build with hdf5 1.10.0

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-science#5094]
Here is the error we are getting:
```
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:161:5: error: cannot initialize a member subobject of type
      'herr_t (*)(H5FD_t *, const char *, const unsigned char *)' (aka 'int (*)(H5FD_t *, const char *, const unsigned char *)') with an rvalue of type 'unsigned long'
    sizeof(H5FD_dsm_fapl_t),    /*fapl_size     */
    ^~~~~~~~~~~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:162:5: error: cannot initialize a member subobject of type 'size_t' (aka 'unsigned long')
      with an lvalue of type 'void *(H5FD_t *)'
    H5FD_dsm_fapl_get,          /*fapl_get      */
    ^~~~~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:168:5: error: cannot initialize a member subobject of type 'herr_t (*)(void *)'
      (aka 'int (*)(void *)') with an lvalue of type 'H5FD_t *(const char *, unsigned int, hid_t, haddr_t)' (aka 'H5FD_t *(const char *, unsigned int, long long, unsigned long
      long)'): different number of parameters (1 vs 4)
    H5FD_dsm_open,              /*open          */
    ^~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:169:5: error: cannot initialize a member subobject of type
      'H5FD_t *(*)(const char *, unsigned int, hid_t, haddr_t)' (aka 'H5FD_t *(*)(const char *, unsigned int, long long, unsigned long long)') with an lvalue of type
      'herr_t (H5FD_t *)' (aka 'int (H5FD_t *)'): different number of parameters (4 vs 1)
    H5FD_dsm_close,             /*close         */
    ^~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:170:5: error: cannot initialize a member subobject of type 'herr_t (*)(H5FD_t *)'
      (aka 'int (*)(H5FD_t *)') with an lvalue of type 'int (const H5FD_t *, const H5FD_t *)': different number of parameters (1 vs 2)
    H5FD_dsm_cmp,               /*cmp           */
    ^~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:177:5: error: cannot initialize a member subobject of type
      'herr_t (*)(H5FD_t *, H5FD_mem_t, hid_t, haddr_t, hsize_t)' (aka 'int (*)(H5FD_t *, H5F_mem_t, long long, unsigned long long, unsigned long long)') with an lvalue of type
      'haddr_t (const H5FD_t *, H5FD_mem_t)' (aka 'unsigned long long (const H5FD_t *, H5F_mem_t)'): different number of parameters (5 vs 2)
    H5FD_dsm_get_eoa,           /*get_eoa       */
    ^~~~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:178:5: error: cannot initialize a member subobject of type
      'haddr_t (*)(const H5FD_t *, H5FD_mem_t)' (aka 'unsigned long long (*)(const H5FD_t *, H5F_mem_t)') with an lvalue of type 'herr_t (H5FD_t *, H5FD_mem_t, haddr_t)'
      (aka 'int (H5FD_t *, H5F_mem_t, unsigned long long)'): different number of parameters (2 vs 3)
    H5FD_dsm_set_eoa,           /*set_eoa       */
    ^~~~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:179:5: error: cannot initialize a member subobject of type
      'herr_t (*)(H5FD_t *, H5FD_mem_t, haddr_t)' (aka 'int (*)(H5FD_t *, H5F_mem_t, unsigned long long)') with an lvalue of type 'haddr_t (const H5FD_t *)'
      (aka 'unsigned long long (const H5FD_t *)'): different number of parameters (3 vs 1)
    H5FD_dsm_get_eof,           /*get_eof       */
    ^~~~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:181:5: error: cannot initialize a member subobject of type
      'herr_t (*)(H5FD_t *, hid_t, void **)' (aka 'int (*)(H5FD_t *, long long, void **)') with an lvalue of type 'herr_t (H5FD_t *, H5FD_mem_t, hid_t, haddr_t, size_t, void *)'
      (aka 'int (H5FD_t *, H5F_mem_t, long long, unsigned long long, unsigned long, void *)'): different number of parameters (3 vs 6)
    H5FD_dsm_read,              /*read          */
    ^~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:182:5: error: cannot initialize a member subobject of type 'herr_t (*)(H5FD_t *, H5FD_mem_t,
      hid_t, haddr_t, size_t, void *)' (aka 'int (*)(H5FD_t *, H5F_mem_t, long long, unsigned long long, unsigned long, void *)') with an lvalue of type 'herr_t (H5FD_t *,
      H5FD_mem_t, hid_t, haddr_t, size_t, const void *)' (aka 'int (H5FD_t *, H5F_mem_t, long long, unsigned long long, unsigned long, const void *)'): type mismatch at 6th
      parameter ('void *' vs 'const void *')
    H5FD_dsm_write,             /*write         */
    ^~~~~~~~~~~~~~
/Users/michkapopoff/repo/paraview/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc/XdmfH5Driver.cxx:189:5: error: excess elements in scalar initializer
    H5FD_FLMAP_SINGLE           /*fl_map        */
    ^
/usr/local/include/H5FDpublic.h:117:27: note: expanded from macro 'H5FD_FLMAP_SINGLE'
#define H5FD_FLMAP_SINGLE {   
```

**Comment by iMichka** [comment]
Issue opened upstream: https://gitlab.kitware.com/paraview/paraview/issues/17160

**Comment by iMichka** [comment]
Quickfix on our side: rollback to hdf5@1.8 for paraview: #5082

**Comment by iMichka** [comment]
Fixed with https://github.com/Homebrew/homebrew-science/pull/5167
