### ISSUE TITLE
opencv3 failed to build on MacOS Sierra 10.12

### ISSUE THREAD

**Issue by Hey-Red-Chan** [Homebrew/homebrew-science#4509]
I typed 
`brew install openCV3 --with-python3`
in the terminal and the error is as follows:

==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
...
[ 66%] Built target opencv_shape
/tmp/opencv3-20161022-74513-13aty4f/opencv-3.1.0/modules/videoio/src/cap_qtkit.mm:46:9: fatal error: 'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>
        ^
1 error generated.
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2

It seems the latest update has already replaced QTKit with CVKit.

Will be grateful if anyone can solve the problem.

**Comment by Hey-Red-Chan** [comment]
..oh fine it's a duplicate of #4303

**Comment by dpo** [comment]
Yep.
