### PR TITLE
icu4c: Revisions and upgrades

### PR DESCRIPTION
**Pull request by skystrife**
### Have you:
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
### Updates to existing formula: have you
- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?
### Changes

icu4c got a version bump (see Homebrew/homebrew-core#183). This PR contains revision bumps and new package versions for packages that depend on it.

### CODE REVIEW

**Comment by skystrife** [comment]
Oh man...

I have no idea what this is about in the CI:

```
Error: No available formula with the name "undefined method `bottle' for Formulary::FormulaNamespace6b8466e8dacd2bd9089e08751d83911d:Module" 
```

...and it looks like libfolia doesn't compile on OS 10.9. (Must be a difference in clang version?)

Is it OK to just make it require Yosemite for now?

**Comment by dpo** [comment]
For reference, the error is
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I../include -std=c++0x -g -O3 -g -O2 -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2 -I/usr/local/Cellar/icu4c/57.1/include -I/usr/local/Cellar/ticcutils/0.7_1/include -c folia_document.cxx -o folia_document.o >/dev/null 2>&1
folia_properties.cxx:1138:104: error: chosen constructor is explicit in copy-initialization
  static const map<ElementType, set<ElementType> > typeHierarchy = {      { AbstractAnnotationLayer_t, {  } },
                                                                                                       ^~~~
```
It doesn't even build with gcc-5 on 10.9:
```
libtool: link: g++-5 -std=c++0x -g -O3 -g -O2 -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2 -I/usr/local/Cellar/icu4c/57.1/include -I/usr/local/Cellar/ticcutils/0.7_1/include -o .libs/folialint folialint.o -Wl,-bind_at_load  ./.libs/libfolia.dylib -L/usr/local/Cellar/ticcutils/0.7_1/lib -L/usr/local/Cellar/icu4c/57.1/lib -L/usr/local/Cellar/libxml2/2.9.3/lib -lticcutils -licui18n -licuuc -licudata -licuio -lxml2
Undefined symbols for architecture x86_64:
  "TiCC::CL_Options::extract(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)", referenced from:
      _main in folialint.o
```

**Comment by ilovezfs** [comment]
Thanks for the PR @skystrife. libfolia and ucto are now fixed in https://github.com/Homebrew/homebrew-science/pull/6160 and https://github.com/Homebrew/homebrew-science/pull/6163. vislcg3 will need a bit more attention than just a revision bump in a separate PR.
