### ISSUE TITLE
import cv2 fails and cannot find module once OpenCV3 has been installed via homebrew on Mac OS Sierra with xcode 8.1

### ISSUE THREAD

**Issue by codermw** [Homebrew/homebrew-science#4571]
### Indicate troubleshooting steps taken

I installed without errors using `brew install opencv3 --HEAD` and `brew link --force opencv3 --HEAD --overwrite` 

### Bug reports / build errors:
I still can't import CV2 and get the error "ImportError: No module named cv2".

#### Brief summary of issue:
I can see the cv2.so file in /usr/local/opt/opencv3/lib/python2.7/site-packages, and the cvopen3.pth is in /usr/local/lib/python2.7/site-packages/ but it still doesn't seem to be linking properly.... any ideas on how to fix this?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by Knoose** [comment]
I seem to be having the same issue.

**Comment by hugochaton** [comment]
same for me

**Comment by rofoto** [comment]
Even with brew link -force you must still manually add the path to opencv in your xcode project. 

![screen shot 2016-12-01 at 7 18 06 am](https://cloud.githubusercontent.com/assets/13305754/20775537/62ee4fd8-b796-11e6-9f91-e463c1b636fc.png)

i am still unable to compile and run after this but at least the libraries link.

If anyone can figure out how to make to get opencv3 to work in xcode 8.1 I would be grateful.

**Comment by Schultzer** [comment]
@codermw 

### Have you linked python.? 
`brew link python` 

### If not installed
`brew install python` 

### Direct the local python path to homebrew python
`mkdir -p /Users/username/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/username/Library/Python/2.7/lib/python/site-packages/homebrew.pth
`

### Try a reinstall of homebrew packages
`brew remove --force $(brew list)`

### Or try OpenCV 3.2
#4759

**Comment by tdsmith** [comment]
Please open a new ticket if you're still having trouble.
