### ISSUE TITLE
Octave install error after updating to Xcode 8.0

### ISSUE THREAD

**Issue by lianne** [Homebrew/homebrew-science#4305]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
  ==> Reinstalling homebrew/science/octave with --with-java
  ==> Using Homebrew-provided fortran compiler.
  This may be changed by setting the FC environment variable.
  ==> Downloading https://ftpmirror.gnu.org/octave/octave-4.0.3.tar.gz
  Already downloaded: /Users/gino/Library/Caches/Homebrew/octave-4.0.3.tar.gz
  ==> Downloading http://hg.savannah.gnu.org/hgweb/octave/raw-rev/e870a68742a6
  Already downloaded: /Users/gino/Library/Caches/Homebrew/octave--patch-  0ddcd8dd032be79d5a846ad2bc190569794e4e1a33ce99f25147d70ae6974682
  ==> Downloading http://savannah.gnu.org/bugs/download.php?file_id=37717
  Already downloaded: /Users/gino/Library/Caches/Homebrew/octave--patch-  feeaad0d00be3008caef2162b549c42fd937f3fb02a36d01cde790a589d4eb2d.php
  ==> Patching
  ==> Applying e870a68742a6
  patching file libgui/src/octave-dock-widget.cc
  ==> Applying download.php
  patching file libinterp/Makefile.in
  ==> ./configure --prefix=/usr/local/Cellar/octave/4.0.3_4 --enable-dependency-tracking --enable-link-all-dep
  ==> make all
  Last 15 lines from /Users/gino/Library/Logs/Homebrew/octave/02.make:
  _GL_CXXALIAS_SYS (mkostemp, int, (char * /*template*/, int /*flags*/));
  ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../libgnu/stdio.h:271:45: note: expanded from macro '_GL_CXXALIAS_SYS'
        static rettype (*func) parameters = ::func;  \
                                          ~~^
  1 error generated.
  make[3]: *** [array/array_libarray_la-Array-b.lo] Error 1
  make[3]: *** Waiting for unfinished jobs....
  1 error generated.
  make[3]: *** [array/array_libarray_la-Array-ch.lo] Error 1
  1 error generated.
  make[3]: *** [array/array_libarray_la-Array-C.lo] Error 1
  make[2]: *** [all] Error 2
  make[1]: *** [all-recursive] Error 1
  make: *** [all] Error 2

  READ THIS: https://git.io/brew-troubleshooting
  If reporting this issue please do so at (not Homebrew/brew):
    https://github.com/Homebrew/homebrew-science/issues

  These open issues may also help:
  Octave 4.0.3_3 missing dependencies on lcms and libpng-1.5?     https://github.com/Homebrew/homebrew-science/issues/4220
  Octave (--with-gui) failed to build on 10.11 https://github.com/Homebrew/homebrew-  science/issues/3387

#### Brief summary of issue:
I am not able to reinstall octave after having updated Xcode to the last version 8.0
 
#### The complete command that you issued:
brew reinstall octave --with-java 


Many thanks.

  Luigi

**Comment by dpo** [comment]
The issue template asks you to provide the gist logs. Please provide all the information requested so we can try to help you.

**Comment by lianne** [comment]
sorry, here they are:
https://gist.github.com/3543451ed050665f4541923d30c22234
thanks a lot.

  Luigi

**Comment by ilovezfs** [comment]
yup, reproducible.

**Comment by ilovezfs** [comment]
@lianne @dpo @schoeps this works around it
```
diff --git a/octave.rb b/octave.rb
index d4bf133..1e720f3 100644
--- a/octave.rb
+++ b/octave.rb
@@ -240,7 +240,7 @@ class Octave < Formula
       inreplace "src/mkoctfile.in.cc", /%OCTAVE_CONF_OCT(AVE)?_LINK_(DEPS|OPTS)%/, '""'
     end
 
-    system "./configure", *args
+    system "./configure", "ac_cv_func_mkostemp=no", *args
     system "make", "all"
     system "make", "check" if build.with? "test"
     system "make", "install"
```

**Comment by dpo** [comment]
For reference, the error was
```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/assert.h:44:
../libgnu/stdlib.h:668:19: error: no member named 'mkostemp' in the global namespace
_GL_CXXALIAS_SYS (mkostemp, int, (char * /*template*/, int /*flags*/));
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libgnu/stdlib.h:267:45: note: expanded from macro '_GL_CXXALIAS_SYS'
      static rettype (*func) parameters = ::func;  \
                                          ~~^
```

**Comment by schoeps** [comment]
@dpo @ilovezfs We should not invest too much time into 4.0.3 since 4.2rc1 is already available. Shall I add an pull request already for the rc? (formula is already available)

**Comment by ilovezfs** [comment]
@schoeps yes, please. Do you mind submitting the PR as 4.2 not 4.2-rc1? We can always push a 4.2.1 if needed

**Comment by ilovezfs** [comment]
Closing this since it will be fixed by forthcoming superenv changes.

**Comment by ilovezfs** [comment]
@lianne if you `brew update` this should now be fixed due to https://github.com/Homebrew/brew/pull/970.

**Comment by lianne** [comment]
yes, now it works also with the original octave formula (without applying your patch of yesterday).

**Comment by ilovezfs** [comment]
@lianne excellent. thanks for testing!

**Comment by tomasdikk** [comment]
Dear community, having difficulties `brew install octave` as well, failing in make. (MacOS 10.12, Xcode 8.0)

Here's https://gist.github.com/ccf57ee1f0b0c0cfecc514faa7d32900

Many thanks for your help, appreciate your great work and efforts!

(I also noticed the hdf5 formula points to `https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2` which causes a 404, apparently it's now at `https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2`)

**Comment by schoeps** [comment]
You seem to have the same problem as @lianne but it should be fixed by now. Did you do a `brew update` and `brew upgrade` before? c.f. also https://github.com/Homebrew/homebrew-science/issues/4220

**Comment by tomasdikk** [comment]
Dear schoeps, many thanks for your support and for getting back.

Yes, it's still here after `brew update` and `brew upgrade` on my side unfortunately. Not sure why though.

When checking `../Logs/Homebrew/octave/02.make` I have similar issues as mentioned above by dpo:

```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/assert.h:44:
../libgnu/stdlib.h:668:19: error: no member named 'mkostemp' in the global namespace
_GL_CXXALIAS_SYS (mkostemp, int, (char * /*template*/, int /*flags*/));
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libgnu/stdlib.h:267:45: note: expanded from macro '_GL_CXXALIAS_SYS'
      static rettype (*func) parameters = ::func;  \
                                          ~~^
```

Thanks also for the issue #4220, looks similar, no issues with `-llcms` or '-lpng15' though. Investigating. Not the `lvecLibFort` case sensitivity issue either. Trying to figure out right now if there's a workable solution in #4220?

Thanks again for helping out!

**Comment by ilovezfs** [comment]
@tomasdikk since that option is now set in brew itself, I'm afraid you may have been bitten by https://twitter.com/MacHomebrew/status/763686348041641984

**Comment by jarfk6** [comment]
I have this exact same problem on OSx 10.12 (Sierra). I've reset git in case I had the update bug (as mentioned by ilovezfs), I've uninstalled XCode and only have the Command Line Tools installed. homebrew is up to date and brew doctor says I'm ready to brew.

https://gist.github.com/dcff5ebacdacf765ad4739de7778fb84

```
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew install octave
==> Installing octave from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://ftpmirror.gnu.org/octave/octave-4.0.3.tar.gz
Already downloaded: /Users/Amanda/Library/Caches/Homebrew/octave-4.0.3.tar.gz
==> Downloading http://hg.savannah.gnu.org/hgweb/octave/raw-rev/e870a68742a6
Already downloaded: /Users/Amanda/Library/Caches/Homebrew/octave--patch-0ddcd8dd032be79d5a846ad2bc190569794e4e1a33ce99f25147d70ae6974682
==> Downloading http://savannah.gnu.org/bugs/download.php?file_id=37717
Already downloaded: /Users/Amanda/Library/Caches/Homebrew/octave--patch-feeaad0d00be3008caef2162b549c42fd937f3fb02a36d01cde790a589d4eb2d.php
==> Patching
==> Applying e870a68742a6
patching file libgui/src/octave-dock-widget.cc
==> Applying download.php
patching file libinterp/Makefile.in
==> ./configure --prefix=/usr/local/Cellar/octave/4.0.3_4 --enable-dependency-tr
==> make all
Last 15 lines from /Users/Amanda/Library/Logs/Homebrew/octave/02.make:
_GL_CXXALIAS_SYS (mkostemp, int, (char * /*template*/, int /*flags*/));
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libgnu/stdio.h:271:45: note: expanded from macro '_GL_CXXALIAS_SYS'
      static rettype (*func) parameters = ::func;  \
                                          ~~^
1 error generated.
make[3]: *** [array/array_libarray_la-Array-b.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
make[3]: *** [array/array_libarray_la-Array-ch.lo] Error 1
make[3]: *** [array/array_libarray_la-Array-C.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by schoeps** [comment]
Can you check if the same problem occurs with the 4.2 release candidate?
`brew install https://raw.githubusercontent.com/schoeps/homebrew-science/master/octave.rb --without-qt5`

If you want 4.0.3 you try to manually edit the formula as described above?
e.g. open an editor with 
`edit /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/octave.rb`
and change the line
`system "./configure", *args`
to
`system "./configure", "ac_cv_func_mkostemp=no", *args`

I do not know why this is necessary.

**Comment by jarfk6** [comment]
$ brew install https://raw.githubusercontent.com/schoeps/homebrew-science/master/octave.rb --without-qt5
######################################################################## 100.0%
Warning: Calling MacOS.clang_version is deprecated!
Use DevelopmentTools.clang_version instead.
/Users/Amanda/Library/Caches/Homebrew/Formula/octave.rb:23:in `<class:Octave>'

qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

**Comment by schoeps** [comment]
@ilovezfs: Wasn't the syntax `brew install http://url/file.rb` supported?

**Comment by ilovezfs** [comment]
The problem above is in the formula, which is using a deprecated method.

**Comment by schoeps** [comment]
Thanks! I fixed the formula for the release candidate (4.2.0 rc2). Maybe you want to try it:

`brew install https://raw.githubusercontent.com/schoeps/homebrew-science/octave/octave.rb --without-qt5`

**Comment by semenyukdmitriy** [comment]
Changing `system "./configure", *args` to `system "./configure", "ac_cv_func_mkostemp=no", *args` in the formula file (locally) fixed the issue for me.

**Comment by ilovezfs** [comment]
superenv sets that value, so that means your brew is outdated if that fixes anything
