### ISSUE TITLE
minc does not compile on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by stwito** [Homebrew/homebrew-science#2927]
I tried to install minc (2.1.13) on OS X 10.11. However, compiling failed:

libsrc2/hyper.c:773:4: error: non-void function 'miget_real_value_hyperslab' should return a value [-Wreturn-type]
          return;

Apparently, this problem was reported for other OS X version and has been signed off as fixed. However, with El Capitan it has come up again.

**Comment by Moisan** [comment]
`minc` is now considered obsolete on the [upstream repository page](https://github.com/BIC-MNI/minc). It has been replaced by [`libminc`](https://github.com/BIC-MNI/libminc) and [`minc-tools`](https://github.com/BIC-MNI/minc-tools). I would advise to the maintainers to remove this formula and create two different formulae for those new projects. I will try to submit a PR for libminc first and see if this error is still present.
