### PR TITLE
Trilinos 12.0.1 (fix)

### PR DESCRIPTION
**Pull request by davydden**
propagate openblas dependency to depends_on packages.

### CODE REVIEW

**Comment by davydden** [comment]
@dpo this PR solve the mentioned in the above issue. Should be good to merge.

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
just tested it on `kubuntu`, works fine `brew install trilinos --with-openblas --without-python --without-scotch --without-x11`

**Comment by davydden** [comment]
@dpo shall we merge it as it fixes the current bug in Trilinos formula? I suppose bottles are still not possible for trlinos due to bot time out.

**Comment by dpo** [comment]
I'm building locally to be sure. Will pull if all is well.

**Comment by davydden** [comment]
sure!

**Comment by davydden** [comment]
Interesting, it seems now Jenkins can properly test trilinos. At least on Yosemite seems that everything passes. Does it mean there will be bottles?

**Comment by dpo** [comment]
Could be. I don't recall the 10.8 build errors though:
```
In file included from /tmp/trilinos20150903-88813-1kb2q7/trilinos-12.0.1-Source/packages/Sundance/Playa/tests/Solver/EigenTest.cpp:77:
/tmp/trilinos20150903-88813-1kb2q7/trilinos-12.0.1-Source/packages/Sundance/Playa/src/PlayaAnasaziEigensolverImpl.hpp:239:11: error: no matching member function for call to 'real'
    ew[i].real(sol.Evals[i].realpart);
    ~~~~~~^~~~
/tmp/trilinos20150903-88813-1kb2q7/trilinos-12.0.1-Source/packages/Sundance/Playa/tests/Solver/EigenTest.cpp:134:38: note: in instantiation of member function 'Playa::AnasaziEigensolver<double>::solve' requested here
    Eigensolver<double> solver = new AnasaziEigensolver<double>(solverParams);
                                     ^
/usr/include/c++/4.2.1/complex:1199:20: note: candidate function not viable: requires 0 arguments, but 1 was provided
  complex<double>::real()
                   ^
/usr/include/c++/4.2.1/complex:1203:20: note: candidate function not viable: requires 0 arguments, but 1 was provided
  complex<double>::real() const
                   ^
In file included from /tmp/trilinos20150903-88813-1kb2q7/trilinos-12.0.1-Source/packages/Sundance/Playa/tests/Solver/EigenTest.cpp:77:
/tmp/trilinos20150903-88813-1kb2q7/trilinos-12.0.1-Source/packages/Sundance/Playa/src/PlayaAnasaziEigensolverImpl.hpp:240:11: error: no matching member function for call to 'imag'
    ew[i].imag(sol.Evals[i].imagpart);
    ~~~~~~^~~~
/usr/include/c++/4.2.1/complex:1207:20: note: candidate function not viable: requires 0 arguments, but 1 was provided
  complex<double>::imag()
                   ^
/usr/include/c++/4.2.1/complex:1211:20: note: candidate function not viable: requires 0 arguments, but 1 was provided
  complex<double>::imag() const
                   ^
2 errors generated.
```
On my 10.9 system, all is well.

**Comment by davydden** [comment]
weird... i don't see any problems in the qouted code as `real()` can be used to both to get real value and to set it. See: http://en.cppreference.com/w/cpp/numeric/complex/real

which compiler/version is it?

**Comment by davydden** [comment]
oh, i see. My guess is that your GCC `4.2.1` (?)  is terribly old and perhaps at those days there were no second usage function. Try installing the most recent GCC.

**Comment by dpo** [comment]
The excerpt above is taken from the bot's log. It's using
```
-- The C compiler identification is AppleClang 5.1.0.5030040
```

**Comment by davydden** [comment]
A friend of mine has `10.8`, I could try on his machine, but he's on holidays now (for another week, AFAIK)...

**Comment by davydden** [comment]
i messed up numbers, he has `10.9`. I won't be able to test it!..

**Comment by davydden** [comment]
I think i know:  `void real (T val);` is part of C++11 standard, and not in C++98. Most likely that `AppleClang 5.1` does not implement C++11, thus  the compiler error.

I can try disabling `Sundials` if it's installed on `10.8`. How do I check OS-X versions in formula?

**Comment by davydden** [comment]
p.s. here's a link to std::complex::real http://www.cplusplus.com/reference/complex/complex/real/

**Comment by dpo** [comment]
Sundials seems to build fine on 10.8. There's a bottle for it. Sundance seems to be the problem.

**Comment by davydden** [comment]
sorry for a typo it's not `Sundials`, it's Trilinos' Sundance

**Comment by dunn** [comment]
Should be able to fix the ML build with
```ruby
needs :cxx11 if MacOS.version < :mavericks
def install
  ENV.cxx11 if MacOS.version < :mavericks
```

**Comment by dpo** [comment]
Thanks @dunn! That might just do it.

**Comment by davydden** [comment]
you sure it's `MacOS.version < :mavericks` instead of `MacOS.version < :mountain_lion`?

**Comment by dunn** [comment]
It's failing on ML, right? So we want to apply it to that case.  `=< :mountain_lion` would work too.

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
There are now a bunch of messages of the form
```
/tmp/trilinos20150904-34983-1ivi4e1/trilinos-12.0.1-Source/packages/mesquite/testSuite/unit/TQualityMetricTest.cpp:166:5: error: non-constant-expression cannot be narrowed from type 'typename __wrap_iter<unsigned long *>::difference_type' (aka 'long') to 'size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
    std::find(act_idx.begin(),act_idx.end(),exp_idx[0]) - act_idx.begin(),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/trilinos20150904-34983-1ivi4e1/trilinos-12.0.1-Source/packages/mesquite/testSuite/unit/TQualityMetricTest.cpp:166:5: note: override this message by inserting an explicit cast
    std::find(act_idx.begin(),act_idx.end(),exp_idx[0]) - act_idx.begin(),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    static_cast<size_t>(                                                 )
```

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
i know what's going now, i will fix it soon...

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
OMG! Trilinos bottles!

**Comment by dpo** [comment]
@davydden Many thanks for championing this!
