### ISSUE TITLE
Trilinos failed to build on 10.9.2

### ISSUE THREAD

**Issue by eroesler** [Homebrew/homebrew-science#887]
Hi,  I could not build trilinos.   Please see the following gist link for more information.  Thank you in advance for your help.

https://gist.github.com/anonymous/d198b172b02be96338da

**Comment by davydden** [comment]
@dpo there are misprints in TPL_ENABLE_XXX. Should be `ParMETIS`, `Cholmod`, `CSparse`

**Comment by davydden** [comment]
@dpo to make configure work with CSparse one needs to add: 
```
args << "-DCSparse_LIBRARY_NAMES=cxsparse;amd;colamd;suitesparseconfig" if build.with? "suite-sparse"
```

**Comment by dpo** [comment]
@davydden Thanks. I updated the gist (but haven't tested).

**Comment by davydden** [comment]
@dpo so what is your current most complete version of Trilinos which compiles?

**Comment by davydden** [comment]
I currently can install without problems: 
```
--without-python, --release, --with-netcdf, --with-metis, --with-mumps, --with-parmetis, --with-scalapack, --with-superlu, --with-hdf5, --with-hypre
```
via a bit modified version of .rb  :  https://github.com/davydden/homebrew-science/blob/master/trilinos.rb

**Comment by dpo** [comment]
I can't build `--with-hypre`:
````
In file included from /tmp/trilinos-7WCu8i/trilinos-11.12.1-Source/packages/epetraext/test/hypre/hypre_UnitTest.cpp:59:
/tmp/trilinos-7WCu8i/trilinos-11.12.1-Source/packages/epetraext/test/hypre/hypre_Helpers.hpp:54:26: error: qualified reference to 'EpetraExt_HypreIJMatrix' is a constructor name rather than a type wherever a constructor can be declared
EpetraExt_HypreIJMatrix::EpetraExt_HypreIJMatrix* newHypreMatrix(int N, int type);                    ^
````
but I suppose that's why you disabled the `EpetraExt` tests.

**Comment by davydden** [comment]
that's right, i had some `EpetraExt` tests issues... i am fiddling with it the whole evening, so i already forgot what was it exactly.

I am currently trying other dependencies

**Comment by davydden** [comment]
You can notify the developers about this issue here: `trilinos-users@software.sandia.gov`
I already send two this evening ;-)

**Comment by dpo** [comment]
In my formula, everything that works is `:recommended`. Packages are slowly promoted to `:recommended` from `:optional` as I resolve issues. Perhaps I should start a temporary tap for just this formula so it's easier to fork and submit PRs?

**Comment by davydden** [comment]
you can also create a branch and update it along the way. My version is pretty much the same as yours (I added superlu_dist which does not compile anyway). A colleague of mine was about to fiddle with it to make it OpenBlas friendly and compile under LinuxBrew. I could post here if there would be further progress.

**Comment by davydden** [comment]
but maybe you are right and creating a separate tap is easier as one does not have to constantly do `merge rebase` with respect to the master homebrew-science branch... so it is just a separate git repo with 1 branch and 1 file.

**Comment by davydden** [comment]
UPDATE: I was able to compile trilinos with almost everything
```
--without-python --release --with-netcdf --with-metis --with-mumps --with-parmetis --with-scalapack --with-superlu --with-hdf5 --with-hypre --with-scotch --with-adol-c  --with-glpk
```

An option would be to comment and mark as TODO non-working packages  (eigen,petsc,superlu_dist),  and merge to Homebrew-Science until the better solution.

**Comment by dpo** [comment]
@davydden I invited you as collaborator on my tap.

**Comment by dpo** [comment]
I'll set up Travis-CI builds so we can relieve our laptops a bit.

**Comment by dpo** [comment]
Everybody please chime in [here](https://github.com/dpo/homebrew-trilinos).

**Comment by pdo** [comment]
Not sure why I'm being CC'd on this thread.  Maybe it's a mixup  
between pdo and dpo usernames?  I (pdo) have no involvement with the  
homebrew-science project.

Regards,
Paul
