### ISSUE TITLE
"  'brew install hdf5 opencv' failed to build on 10.10"

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#3108]
_From @AnushaManila on December 10, 2015 9:42_

Error : undefined method `desc' for Formulary::Formulae::Hdf5:Class

Could anyone help to solve this issue?

_Copied from original issue: Homebrew/homebrew#46857_

**Comment by bfontaine** [comment]
Please run `brew update` and try again.

**Comment by dpo** [comment]
@AnushaManila Any update?

**Comment by dpo** [comment]
`opencv` was rebuilt on Jan 8th. Please reopen if the issue persists.
