### ISSUE TITLE
blasr fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2538]
```
==> Installing blasr from homebrew/homebrew-science
==> Downloading https://github.com/PacificBiosciences/blasr/archive/smrtanalysis-2.2.tar.gz
==> Downloading from https://codeload.github.com/PacificBiosciences/blasr/tar.gz/smrtanalysis-2.2
######################################################################## 100,0%
==> make STATIC= HDF5INCLUDEDIR=/usr/local/opt/hdf5/include HDF5LIBDIR=/usr/local/opt/hdf5/lib
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [bin/blasr] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [alignment-build] Error 2
```

Logs: https://gist.github.com/36261ac2268c6d410d84

**Comment by dpo** [comment]
This and #2596 are the same issue. I'll close this one because a discussion on the error has begun in #2596.
