### ISSUE TITLE
quorum fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2551]
```
==> Installing quorum from homebrew/homebrew-science
==> Downloading ftp://ftp.genome.umd.edu/pub/QuorUM/quorum-1.0.0.tar.gz
######################################################################## 100,0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/quorum/1.0.0
==> make install
         ^
1 error generated.
make[1]: *** [src/error_correct_reads.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2
```

Logs: https://gist.github.com/d3f412ab69153a9e8685

**Comment by dpo** [comment]
```
In file included from src/error_correct_reads.cc:31:
./include/gzip_stream.hpp:6:10: fatal error: 'ext/stdio_filebuf.h' file not found
#include <ext/stdio_filebuf.h>
         ^
1 error generated.
```
