### PR TITLE
Fix hdf4 support for gnudatalanguage

### LINKED ISSUE #2721: gnudatalanguage failed to build on OSX 10.10.5
When attempting to run `brew install gnudatalanguage -v --with-hdf4`,

I'm getting a build failure that I can't explain; in particular:

    /tmp/gnudatalanguage20150907-21228-1esd8jt/gdl-0.9.5/src/GDLTokenTypes.hpp:70:7: error: expected identifier
                NOP = 59,

Thanks for any ideas.
gist is here: https://gist.github.com/b1283bad253a3c6d7ed6

### PR DESCRIPTION
**Pull request by devonhollowood**
Fixes #2721

### CODE REVIEW

**Comment by dpo** [comment]
Thank you!
