### ISSUE TITLE
opencv3 failed to build on OS X 10.10.5

### ISSUE THREAD

**Issue by JetForMe** [Homebrew/homebrew-science#2733]
Error with 'brew install --c++11'

I can't tell exactly what's going on. OS 10.10.5, Xcode 7 GM seed.

```
$ brew doctor
Your system is ready to brew.
```

https://gist.github.com/anonymous/a6c1a5d066d94499a6a2

Results:

```
$ brew install opencv3 --c++11
==> Installing opencv3 from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3-3.0.0.tar.gz
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20141027.tgz
Already downloaded: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv3/3.0.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_JASPER=OFF -DBUILD_JPEG=OF
==> make
cd /tmp/opencv320150911-90897-x60yhh/opencv-3.0.0/macbuild/modules/imgproc && /usr/local/Cellar/cmake/3.3.1/bin/cmake -E cmake_link_script CMakeFiles/opencv_imgproc.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++     -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden   -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 3.0.0 -current_version 3.0.0 -o ../../lib/libopencv_imgproc.3.0.0.dylib -install_name /tmp/opencv320150911-90897-x60yhh/opencv-3.0.0/macbuild/lib/libopencv_imgproc.3.0.dylib CMakeFiles/opencv_imgproc.dir/src/accum.cpp.o CMakeFiles/opencv_imgproc.dir/src/approx.cpp.o CMakeFiles/opencv_imgproc.dir/src/blend.cpp.o CMakeFiles/opencv_imgproc.dir/src/canny.cpp.o CMakeFiles/opencv_imgproc.dir/src/clahe.cpp.o CMakeFiles/opencv_imgproc.dir/src/color.cpp.o CMakeFiles/opencv_imgproc.dir/src/colormap.cpp.o CMakeFiles/opencv_imgproc.dir/src/connectedcomponents.cpp.o CMakeFiles/opencv_imgproc.dir/src/contours.cpp.o CMakeFiles/opencv_imgproc.dir/src/convhull.cpp.o CMakeFiles/opencv_imgproc.dir/src/corner.cpp.o CMakeFiles/opencv_imgproc.dir/src/cornersubpix.cpp.o CMakeFiles/opencv_imgproc.dir/src/demosaicing.cpp.o CMakeFiles/opencv_imgproc.dir/src/deriv.cpp.o CMakeFiles/opencv_imgproc.dir/src/distransform.cpp.o CMakeFiles/opencv_imgproc.dir/src/drawing.cpp.o CMakeFiles/opencv_imgproc.dir/src/emd.cpp.o CMakeFiles/opencv_imgproc.dir/src/featureselect.cpp.o CMakeFiles/opencv_imgproc.dir/src/filter.cpp.o CMakeFiles/opencv_imgproc.dir/src/floodfill.cpp.o CMakeFiles/opencv_imgproc.dir/src/gabor.cpp.o CMakeFiles/opencv_imgproc.dir/src/generalized_hough.cpp.o CMakeFiles/opencv_imgproc.dir/src/geometry.cpp.o CMakeFiles/opencv_imgproc.dir/src/grabcut.cpp.o CMakeFiles/opencv_imgproc.dir/src/hershey_fonts.cpp.o CMakeFiles/opencv_imgproc.dir/src/histogram.cpp.o CMakeFiles/opencv_imgproc.dir/src/hough.cpp.o CMakeFiles/opencv_imgproc.dir/src/imgwarp.cpp.o CMakeFiles/opencv_imgproc.dir/src/intersection.cpp.o CMakeFiles/opencv_imgproc.dir/src/linefit.cpp.o CMakeFiles/opencv_imgproc.dir/src/lsd.cpp.o CMakeFiles/opencv_imgproc.dir/src/matchcontours.cpp.o CMakeFiles/opencv_imgproc.dir/src/min_enclosing_triangle.cpp.o CMakeFiles/opencv_imgproc.dir/src/moments.cpp.o CMakeFiles/opencv_imgproc.dir/src/morph.cpp.o CMakeFiles/opencv_imgproc.dir/src/phasecorr.cpp.o CMakeFiles/opencv_imgproc.dir/src/pyramids.cpp.o CMakeFiles/opencv_imgproc.dir/src/rotcalipers.cpp.o CMakeFiles/opencv_imgproc.dir/src/samplers.cpp.o CMakeFiles/opencv_imgproc.dir/src/segmentation.cpp.o CMakeFiles/opencv_imgproc.dir/src/shapedescr.cpp.o CMakeFiles/opencv_imgproc.dir/src/smooth.cpp.o CMakeFiles/opencv_imgproc.dir/src/subdivision2d.cpp.o CMakeFiles/opencv_imgproc.dir/src/sumpixels.cpp.o CMakeFiles/opencv_imgproc.dir/src/tables.cpp.o CMakeFiles/opencv_imgproc.dir/src/templmatch.cpp.o CMakeFiles/opencv_imgproc.dir/src/thresh.cpp.o CMakeFiles/opencv_imgproc.dir/src/undistort.cpp.o CMakeFiles/opencv_imgproc.dir/src/utils.cpp.o CMakeFiles/opencv_imgproc.dir/opencl_kernels_imgproc.cpp.o ../../lib/libopencv_hal.a ../../lib/libopencv_core.3.0.0.dylib ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a ../../lib/libopencv_hal.a ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a 
cd /tmp/opencv320150911-90897-x60yhh/opencv-3.0.0/macbuild/modules/imgproc && /usr/local/Cellar/cmake/3.3.1/bin/cmake -E cmake_symlink_library ../../lib/libopencv_imgproc.3.0.0.dylib ../../lib/libopencv_imgproc.3.0.dylib ../../lib/libopencv_imgproc.dylib
[ 28%] Built target opencv_imgproc
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
```

**Comment by tdsmith** [comment]
The error is at
https://gist.github.com/anonymous/a6c1a5d066d94499a6a2#file-02-make-L367-L369:
```
cd /tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/macbuild/modules/imgproc && /usr/local/Library/ENV/4.3/clang++   -DCVAPI_EXPORTS -D__OPENCV_BUILD=1 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden   -DNDEBUG -fPIC -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/3rdparty/ippicv/unpack/ippicv_osx/include -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/macbuild -isystem /usr/local/include/eigen3 -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/modules/imgproc/include -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/modules/imgproc/src -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/macbuild/modules/imgproc -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/modules/hal/include -I/tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/modules/core/include    -o CMakeFiles/opencv_imgproc.dir/src/corner.cpp.o -c /tmp/opencv320150911-80007-1tr2zja/opencv-3.0.0/modules/imgproc/src/corner.cpp
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/IOKit.framework', needed by `lib/libopencv_viz.3.0.0.dylib'.  Stop.
```

No idea what's responsible for that but it's probably exposed by the version of Xcode you're using.

--c++11 is probably a no-op on 10.9+, so you may be able to just use the bottle.

**Comment by JetForMe** [comment]
Oh, good eye. I'll try the bottle. One of our other engineers came up with the build instructions for our code (that relies on OpenCV), but he wasn't pre-10.9, so I don't know if that's necessary or not. I've asked him. Thanks.

**Comment by davrandom** [comment]
Hi,
the title of the bug also applies to me, but the reason for the failure is different.
When I'm doing 
`brew install opencv --with-contrib`
it fails because:

```
In file included from /usr/local/include/eigen3/Eigen/Core:422:
In file included from /usr/local/include/eigen3/Eigen/src/Core/ArrayBase.h:93:
/usr/local/include/eigen3/Eigen/src/Core/../plugins/ArrayCwiseUnaryOps.h:489:14: error: unknown type name 'LgammaReturnType'; did you mean 'DigammaReturnType'?
inline const LgammaReturnType
             ^
/usr/local/include/eigen3/Eigen/src/Core/../plugins/ArrayCwiseUnaryOps.h:471:74: note: 'DigammaReturnType' declared here
typedef CwiseUnaryOp<internal::scalar_digamma_op<Scalar>, const Derived> DigammaReturnType;
                                                                         ^
4 errors generated.
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [all] Error 2
```
also `eigen` is installed with brew.

**Comment by ilovezfs** [comment]
@davrandom it works with eigen-3.2.10 but not eigen-3.3.0

I suggest you report the problem upstream to opencv3

**Comment by tdsmith** [comment]
--with-contrib breaks a lot; be sure you need it.

Closing this ticket since the original issue is a year old and hasn't recurred.
