### ISSUE TITLE
spatialite-gis fails to build on 10.10+

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2555]
```
==> Installing homebrew/science/spatialite-gis
==> Downloading http://www.gaia-gis.it/gaia-sins/spatialite_gis-1.0.0c.tar.gz
######################################################################## 100,0%
==> Downloading https://www.gaia-gis.it/fossil/spatialite_gis/vpatch?from=0506d89e65c692d7&to=0783daf1178ee1dc
Already downloaded: /Library/Caches/Homebrew/spatialite-gis--patch-a82f5f6aef40ec1177fb8a28164c7ad9ea600b18
==> Patching
patching file Classdef.h
patching file Dialogs.cpp
patching file LayerTree.cpp
patching file MapDynamic.cpp
patching file MapView.cpp
patching file Network.cpp
patching file Objects.cpp
patching file OutputMap.cpp
patching file Shapefiles.cpp
patching file SqlHelpers.cpp
patching file TableDialogs.cpp
patching file Main.cpp
==> ./configure --prefix=/usr/local/Cellar/spatialite-gis/1.0.0c
==> make install
      MyFrame::MemoryDbSave() in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [spatialite_gis] Error 1
make: *** [install-recursive] Error 1
```

Logs: https://gist.github.com/79bdd403833c3211cb22

**Comment by cmyk** [comment]
second that

**Comment by dpo** [comment]
For reference, the error is
```
libtool: link: clang++ -I/usr/local/Cellar/wxmac/3.0.2/lib/wx/include/osx_cocoa-unicode-3.0 -I/usr/local/Cellar/wxmac/3.0.2/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -I/usr/local/Cellar/libspatialite/4.3.0/include -o spatialite_gis Bitmaps.o ClassifyDlgs.o Dialogs.o GraphicsDlgs.o LayerTree.o Main.o MapDynamic.o MapView.o MetadataInit.o Network.o Objects.o OutputMap.o Shapefiles.o SqlHelpers.o TableDialogs.o -Wl,-bind_at_load  -liconv -L/usr/local/Cellar/wxmac/3.0.2/lib -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_webview-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_qa-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 -L/usr/local/Cellar/libspatialite/4.3.0/lib -lspatialite -L/usr/local/Cellar/librasterlite/1.1g_1/lib -lrasterlite -L/usr/local/Cellar/freexl/1.0.1/lib -lfreexl -lhpdf -lgeotiff -lgeos_c /usr/local/Cellar/proj/4.9.1/lib/libproj.dylib -lpthread -lm -ltiff -ljpeg -lz
Undefined symbols for architecture x86_64:
  "_sqlite3_backup_finish", referenced from:
      MyFrame::OnMemoryDbLoad(wxCommandEvent&) in Main.o
      MyFrame::MemoryDbSave() in Main.o
  "_sqlite3_backup_init", referenced from:
      MyFrame::OnMemoryDbLoad(wxCommandEvent&) in Main.o
      MyFrame::MemoryDbSave() in Main.o
  "_sqlite3_backup_step", referenced from:
      MyFrame::OnMemoryDbLoad(wxCommandEvent&) in Main.o
      MyFrame::MemoryDbSave() in Main.o
  "_sqlite3_bind_blob", referenced from:
      MyFrame::CreateSymbolBitmaps() in Bitmaps.o
      MyFrame::CreatePatternBitmaps() in Bitmaps.o
      MyFrame::UpdateCurrentEntityGeometry() in Main.o
      MyMapView::DynamicSplitLine() in MapDynamic.o
      MyFrame::CreateNetwork(Network*, wxString&, wxString&, wxString&, wxString&, wxString&, bool, double) in Network.o
      MyFrame::LoadShapefile(wxString&, wxString&, int, wxString&, wxString&, bool, bool) in Shapefiles.o
      IdentifyDialog::OnCmdSave(wxCommandEvent&) in TableDialogs.o
```
https://gist.github.com/anonymous/79bdd403833c3211cb22#file-02-make-L43

**Comment by chryss** [comment]
Same for me.

**Comment by lathropd** [comment]
I'm having the same issue in 10.11.4

**Comment by apjanke** [comment]
For some reason it's not linking to `sqlite`. Adding `depends_on "sqlite"` and `ENV.append "LDFLAGS", "-lsqlite"` to the formula didn't fix it for me. For some reason, the `-lsqlite` flag is still not showing up in the link command.

```
libtool: link: clang++ -I/usr/local/lib/wx/include/osx_cocoa-unicode-3.0 -I/usr/local/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -I/usr/local/Cellar/libspatialite/4.3.0a_3/include -o spatialite_gis Bitmaps.o ClassifyDlgs.o Dialogs.o GraphicsDlgs.o LayerTree.o Main.o MapDynamic.o MapView.o MetadataInit.o Network.o Objects.o OutputMap.o Shapefiles.o SqlHelpers.o TableDialogs.o  -liconv -L/usr/local/lib -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_webview-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_qa-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 -L/usr/local/Cellar/libspatialite/4.3.0a_3/lib -lspatialite -L/usr/local/Cellar/librasterlite/1.1g_2/lib -lrasterlite -L/usr/local/Cellar/freexl/1.0.2/lib -lfreexl -lhpdf -lgeotiff -lgeos_c /usr/local/Cellar/proj/4.9.3/lib/libproj.dylib -lpthread -lm -ltiff -ljpeg -lz
```

Any ideas how to tweak the formula or `spatialite-gui`'s `configure` script to convince it to link `sqlite`?

**Comment by fish2000** [comment]
@apjanke I just pushed up a patch and submitted a PR that alters the formula per your request – specifically, one needs to manually specify `-lsqlite3` in `LDFLAGS` – and while the integration tests haven’t yet completed, I at least can verify that the fix works for me locally. 

q.v. PR https://github.com/Homebrew/homebrew-science/pull/6389 _supra._
