### ISSUE TITLE
gnudatalanguage failed to build on OSX 10.10.5

### ISSUE THREAD

**Issue by jhcsu** [Homebrew/homebrew-science#2721]
When attempting to run `brew install gnudatalanguage -v --with-hdf4`,

I'm getting a build failure that I can't explain; in particular:

    /tmp/gnudatalanguage20150907-21228-1esd8jt/gdl-0.9.5/src/GDLTokenTypes.hpp:70:7: error: expected identifier
                NOP = 59,

Thanks for any ideas.
gist is here: https://gist.github.com/b1283bad253a3c6d7ed6

**Comment by devonhollowood** [comment]
I just ran into the same issue when running `brew install gnudatalanguage --with-hdf4 --with-python`. It seems like the problem comes from the `--with-hdf4` option, since building without it went smoothly for me, although how this leads to the given syntax error (on line 70 of [this file](http://gnudatalanguage.cvs.sourceforge.net/viewvc/gnudatalanguage/gdl/src/GDLTokenTypes.hpp?revision=1.44&view=markup)) is beyond me.

Looking into it a little more, I found that `hdf4` built fine, but didn't get symlinked because of a conflict, namely `ncgen` belonging to `netcdf`. In fact, running the above `brew install` command again prints

```
Error: You must `brew link hdf4` before homebrew/science/gnudatalanguage can be installed
```

So maybe this is related to the issue? I don't know enough about homebrew internals to know for sure but I thought I would post this in case it helped. In the mean time I'm just going to make due without `hdf4` support.

**Comment by ilovezfs** [comment]
please try again now that https://github.com/Homebrew/homebrew-science/pull/4189 has shipped

**Comment by devonhollowood** [comment]
I ran `brew update`, and then `brew install gnudatalanguage --with-python --withhdf4`, and it failed with the same error:

```
devon $ brew install gnudatalanguage --with-python --with-hdf4
==> Installing gnudatalanguage from homebrew/science
==> Downloading https://downloads.sourceforge.net/project/gnudatalanguage/gdl/0.
Already downloaded: /Users/devon/Library/Caches/Homebrew/gnudatalanguage-0.9.5.tar.gz
==> Downloading https://gist.githubusercontent.com/iml/ee107290ee5cd2850190/raw/
Already downloaded: /Users/devon/Library/Caches/Homebrew/gnudatalanguage--patch-b2e9b2c1ed51676e048441b7bfc160488fdf5898b1d1c9396bc58eb85996981e.diff
==> Downloading https://gist.github.com/tschoonj/e01c72165fd2cb9a68c9/raw/514316
Already downloaded: /Users/devon/Library/Caches/Homebrew/gnudatalanguage--patch-937e82f6052aa72576df49046aa57d03593c7ba21d074f2455cd614318b881dd.patch
==> Patching
==> Applying gnudatalanguage.diff
patching file CMakeLists.txt
patching file src/base64.hpp
patching file src/basic_fun.cpp
patching file src/gsl_fun.cpp
patching file ./src/str.cpp
Hunk #1 succeeded at 178 (offset -2 lines).
Hunk #2 succeeded at 189 (offset -2 lines).
Hunk #3 succeeded at 201 (offset -2 lines).
patch unexpectedly ends in middle of line
Hunk #4 succeeded at 209 with fuzz 2 (offset -2 lines).
==> Applying gdl-plplot.patch
patching file CMakeModules/FindPlplot.cmake
patching file src/plotting_contour.cpp
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/devon/Library/Logs/Homebrew/gnudatalanguage/02.make:
In file included from /tmp/gnudatalanguage-20160901-44990-1n9nm01/gdl-0.9.5/src/basegdl.hpp:31:
In file included from /tmp/gnudatalanguage-20160901-44990-1n9nm01/gdl-0.9.5/src/dimension.hpp:24:
In file included from /tmp/gnudatalanguage-20160901-44990-1n9nm01/gdl-0.9.5/src/gdlexception.hpp:24:
In file included from /tmp/gnudatalanguage-20160901-44990-1n9nm01/gdl-0.9.5/src/prognode.hpp:21:
In file included from /tmp/gnudatalanguage-20160901-44990-1n9nm01/gdl-0.9.5/src/dnode.hpp:27:
/tmp/gnudatalanguage-20160901-44990-1n9nm01/gdl-0.9.5/src/GDLTokenTypes.hpp:70:7: error: expected identifier
                NOP = 59,
                    ^
1 error generated.
make[2]: *** [src/CMakeFiles/gdl.dir/hdf_fun.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/CMakeFiles/gdl.dir/hdf_pro.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/gdl.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
gnudatalanguage failed to build on OSX 10.10.5 https://github.com/Homebrew/homebrew-science/issues/2721
```

**Comment by ilovezfs** [comment]
@devonhollowood thanks for checking. This fixes it: https://gist.github.com/ilovezfs/00d95a9ad9e44c8091a1353b2242c33c

**Comment by dpo** [comment]
@devonhollowood Can you confirm that the path fixes the build for you?

**Comment by devonhollowood** [comment]
@dpo Yes, I just tried installing without the patch (which failed with the same old error), and with that patch (which worked!). Thank you.

Incidentally, is there a better way to apply a patch than `curl https://gist.githubusercontent.com/ilovezfs/00d95a9ad9e44c8091a1353b2242c33c/raw/5c2f504334186b6d1f58b064d8cb96013a2027e1/gistfile1.txt | patch -b /usr/local/Library/Taps/homebrew/homebrew-science/gnudatalanguage.rb`? Like is there an option I can pass to `brew install` or something? It wasn't really clear from the manpage. `brew pull` seemed close, but the patch in question wasn't a pull request or commit so it didn't seem to work.

**Comment by dpo** [comment]
@devonhollowood if the patch fixes things, we should simply update the formula to include the patch as @ilovezfs indicated. Would you like to submit a pull request and reference this issue?

**Comment by devonhollowood** [comment]
@dpo done, including running `brew audit --strict --online gnudatalanguage` (which produced no errors). Let me know if I did anything wrong; I'm new to homebrew's contribution process. Also, thanks for letting me get involved!

**Comment by dpo** [comment]
Anytime! Thanks for your contribution!!
