### ISSUE TITLE
phlawd fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2548]
```
==> Installing homebrew/science/phlawd
==> Downloading https://github.com/chinchliff/phlawd/releases/download/3.4a/phlawd_3.4a_src_with_sqlitewrapped_1.3.1.tar.gz
==> Downloading from https://s3.amazonaws.com/github-cloud/releases/5273629/7e1bf076-b771-11e3-8d6e-2aa9690132c4.gz?response-content-disposition=attachment%3B%20filename%3Dphlawd_3.4a_src_with_sqlitewrap
######################################################################## 100,0%
==> Patching
patching file src/Makefile.MAC
==> make -C sqlitewrapped-1.3.1
==> make -C src -f Makefile.MAC
1 error generated.
make: *** [SQLiteProfiler.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [SQLiteConstructor.o] Error 1
```

Logs: https://gist.github.com/64eb23f7afa7bf48593b

**Comment by dpo** [comment]
```
SQLiteConstructor.cpp:46:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^
```
This formula is missing a `needs :openmp`. PR welcome.

**Comment by bfontaine** [comment]
Thank you @dpo, I submitted #2566.
