### ISSUE TITLE
blast: Fails to build on Linux

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3458]
_From @awitney on March 21, 2016 16:48_

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
I am trying to install blast. This is the error:

```
compilation terminated.
make[3]: *** [test_boost.o] Error 1
make[3]: Leaving directory `/tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
FAILED: src/corelib/Makefile.test_boost.lib
make[3]: Entering directory `/tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
/bin/rm -f libtest_boost.a .test_boost.dep .libtest_boost.a.stamp
/bin/rm -f /tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libtest_boost.a /tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.test_boost.dep \
    /tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libtest_boost-static.a /tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.test_boost-static.dep
make[3]: Leaving directory `/tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
make[2]: *** [all.nonusr] Error 2
make[2]: Leaving directory `/tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
make[1]: *** [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build'
make: *** [all] Error 2
```

I notice that in 

```
/home/adam/.cache/Homebrew/Logs/blast/02.make
```

gcc is set as

```
CC: /usr/bin/gcc
CXX: /usr/bin/g++
OBJC: /usr/bin/gcc
OBJCXX: /usr/bin/g++
```

I don't know if this is causing the install to fail, but I can't seem to force it to use the gcc in .linuxbrew/bin

Any help would be appreciated?

_Copied from original issue: Linuxbrew/linuxbrew#966_

**Comment by sjackman** [comment]
Please report `brew gist-logs blast`

**Comment by awitney** [comment]
$ brew gist-logs blast
https://gist.github.com/0853a382ef228b464a40

**Comment by sjackman** [comment]
It looks as though `blast` doesn't build with `boost` 1.60.0:
https://gist.github.com/anonymous/0853a382ef228b464a40#file-02-make-L193-L195
```
Updating dependency information for /tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/src/corelib/test_boost.cpp.
/tmp/blast20160321-4137-1uinmk1/ncbi-blast-2.2.31+-src/c++/src/corelib/test_boost.cpp:73:40: fatal error: boost/test/test_observer.hpp: No such file or directory
 #include <boost/test/test_observer.hpp>
```

**Comment by sjackman** [comment]
Duplicate of https://github.com/Homebrew/homebrew-science/issues/2705#issuecomment-179524097

**Comment by sjackman** [comment]
It doesn't look as though there's a solution for this issue yet. You may want to try an older version of boost.

**Comment by DwinGrashof** [comment]
I've installed boost 1.59 in the hope to succesfully install CEGMA with Linuxbrew/Homebrew.
This didn't wor for me. I still have the same error as listed above. Is there anyone who found a way to fix this issue?

Kind regards,
Dwin

**Comment by sjackman** [comment]
As a workaround, you could use upstream's precompiled executables:
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.3.0+-x64-linux.tar.gz
See http://www.ncbi.nlm.nih.gov/books/NBK52640/

**Comment by sjackman** [comment]
This issue has moved to https://github.com/Homebrew/homebrew-science/issues/2705
