### ISSUE TITLE
OpenCV install fails on MacOS Sierra (10.12) at 16%

### ISSUE THREAD

**Issue by barronlroth** [Homebrew/homebrew-science#4303]
### Indicate troubleshooting steps taken

- [ YES ] Ran `brew update` and retried your prior step?
- [ YES ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ YES ] Checked that a similar issue hasn't already been filed?
- [ YES ] Looked up the software bug tracker if reporting a build error?
- [ YES ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
OpenCV installation fails at `[ 16%] Built target opencv_video`

#### The complete command that you issued:
brew install opencv

#### Gist with output of `brew doctor`:
In Gist below 

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/barronlroth/2860981929c4ebbdb2dffbd1f72bbebd

#### Output of `brew config`:
In gist above^

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
For reference, the error is
```
cd /tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/macbuild/modules/video && /usr/local/Library/Homebrew/shims/super/clang++   -DCVAPI_EXPORTS -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/video/perf -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/video/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/calib3d/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/features2d/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/highgui/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/imgproc/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/flann/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/core/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/ts/include -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/macbuild/modules/video -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/video/src -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/video/test -I/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/macbuild -isystem /usr/local/include/eigen3  -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fPIC   -o CMakeFiles/opencv_video.dir/src/kalman.cpp.o -c /tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/video/src/kalman.cpp
/tmp/opencv-20160913-71239-42tmik/opencv-2.4.13/modules/highgui/src/cap_qtkit.mm:46:9: fatal error: 'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>
        ^
```

**Comment by barronlroth** [comment]
@dpo Good call. Any tips on finding QTKit/QTKit.h?

**Comment by Noctem** [comment]
The problem also occurs on non-Sierra systems with Xcode 8.

**Comment by barronlroth** [comment]
@Noctem And Homebrew doctor forces Xcode 8 when running Sierra.

**Comment by heinemml** [comment]
What @Noctem means, this also now breaks on El Capitan with the Release of XCode 8. Which is more or less an automatic update.

**Comment by dpo** [comment]
This is more or less a duplicate of #4104. See also https://github.com/opencv/opencv/pull/7159.

**Comment by sromberg** [comment]
Confirmed for 10.11 on XCode 8:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

$ clang++ -v
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Compile error at:
```
/tmp/opencv-20160917-26901-4448l6/opencv-2.4.13/modules/highgui/src/cap_qtkit.mm:46:9: fatal error: 'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>
        ^
1 error generated.
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_qtkit.mm.o] Error 1
```

**Comment by zo7** [comment]
In case anyone's wondering, you can [download an older version of Xcode](https://developer.apple.com/download/more/) and choose it with `xcode-select` and OpenCV will build correctly (10.11)

**Comment by iMicknl** [comment]
@zo7 unfortunately this doesn't work on 10.12. I am trying to run it with Xcode 7.3, but still the same error at 16%.

**Comment by vinyldarkscratch** [comment]
The problem is that [QTKit is deprecated since 10.9, and it was stated that it will be removed in a future version](https://developer.apple.com/reference/qtkit).  It seems that Sierra is that very version.  [AVFoundation](https://developer.apple.com/reference/avfoundation) is the library they say should be used in it's place.

**Comment by xanview** [comment]
Same problem: "fatal error: 'QTKit/QTKit.h' file not found"

**Comment by barronlroth** [comment]
@xanview installing the --HEAD version should work.

**Comment by yujun1214** [comment]
I met the same problem, was it fixed?

**Comment by mhulse** [comment]
> @xanview installing the --HEAD version should work.

So, like: `brew tap homebrew/science && brew install --HEAD opencv3`? :)

**Comment by ablyeom** [comment]
@mhulse 
In my case, I ran like: `brew reinstall opencv3 --HEAD --with-ffmpeg --with-tbb --with-contrib`

**Comment by mhulse** [comment]
Thanks for the reply @ablyeom. Do you happen to know if I need to add anything to my path after install? When I run `which opencv3` or `which opencv`, I get nothing. :(

**Comment by ablyeom** [comment]
@mhulse
OpenCV(which you installed) is not executable file. it's a library for computer vision.

In my case, **`lib`** and **`include`** directories are located under `/usr/local/Cellar/opencv3/HEAD-dd379ec_4` directory.

And! I am starter of opencv, actually... so I cannot help you properly.T-T

**Comment by mhulse** [comment]
Thanks @ablyeom, I really appreciate it! 👍 I'm new to `opencv` too. I just assumed it would show up on my path after installation. I'm trying to use it in conjunction with a node package … Anyway, starter here too! Thanks again!

**Comment by Lv1204** [comment]
@ablyeom that works. Thanks a lot!

**Comment by ablyeom** [comment]
@Lv1204 I am glad to be of help :)

I found option to install with new numpy-1.11.2, instead of dependency numpy-1.11.1.
If you want to use python, append `--without-numpy` option.
To use this option, you should install `numpy` using brew.

**Comment by xudesheng** [comment]
I downloaded latest code from OpenCV and it seems like they replaced qtkit.h with AVFoundation. if I compile with XCode, now it can pass 16% and move on. However, it seems like brew is still using old code and therefore it continues fail.
sadly I have uninstalled old version installed by brew and now I can't come back.

**Comment by kosma** [comment]
> downloaded latest code from OpenCV and it seems like they replaced qtkit.h with AVFoundation. if I compile with XCode, now it can pass 16% and move on. However, it seems like brew is still using old code and therefore it continues fail.
> sadly I have uninstalled old version installed by brew and now I can't come back.

@xudesheng Use `brew install opencv --HEAD` as a workaround.

**Comment by dpo** [comment]
Fixed by #4336.

**Comment by Walid-Ahmed** [comment]
I installed without errors using
brew install opencv --HEAD

still I can not import CV2 and get the error "ImportError: No module named cv2"

**Comment by yongduek** [comment]
After removing all the opencv versions, I installed without errors using
``brew install opencv3 --HEAD``
and 
 ``brew link --force opencv3 --HEAD --overwrite``

No problem to compile and run an example in ``samples/cpp``.

**Comment by codermw** [comment]
I installed without errors using `brew install opencv3 --HEAD` and `brew link --force opencv3 --HEAD --overwrite` but I still can't import CV2 and get the error "ImportError: No module named cv2".
I can see the cv2.so file in /usr/local/opt/opencv3/lib/python2.7/site-packages, and the cvopen3.pth is in /usr/local/lib/python2.7/site-packages/ but it still doesn't seem to be linking properly.... any ideas on how to fix this?

**Comment by ghattab** [comment]
@yongduek's solution works!
```
>>> cv2.__version__
'3.1.0-dev'
```

**Comment by NilanjPatel** [comment]
@codermw @Walid-Ahmed  have you solved your issue of importing error for cv3, if you have solution than please guide me

**Comment by YuBPan** [comment]
```
cd /usr/local/lib/python2.7/site-packages
ln -s /usr/local/Cellar/opencv3/HEAD-7d5fd6a_4/lib/python2.7/site-packages/cv2.so cv2.so

python -c "import cv2;  print cv2.__version__"
3.1.0-dev
```
make sure use the right path to source file `cv.so` when creating soft link

**Comment by wumengfei** [comment]
it gives me a hint
```
To install it, run:
  brew install homebrew/science/opencv3
```

**Comment by Ling-wei** [comment]
Anybody here...I updated my macOS to 10.12 last month ,before that I had already install opencv 3 successfully...For some reason,I need to intall opencv 2.4.9 with xcode 8....When I made the file, I met the same question. I tried everything to fix the problem  about 'QTKit/QTKit.h', but the process is still stuck at 31% with a fatal error.HELP!!!!!("brew install opencv3 --HEAD" doesn't work for me..)

**Comment by iMichka** [comment]
Please don't post on old closed issues, and open a new issue (and fill out the issue template).
