### PR TITLE
bowtie2 2.2.9

### PR DESCRIPTION
**Pull request by sjackman**
Possibly related to #3440.

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/4336/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_science_bowtie2/
```
clang++ -O3 -m64 -msse2  -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2  -funroll-loops -g3 -L /usr/local/lib -DPOPCNT_CAPABILITY -DWITH_TBB\"" -L /usr/local/lib -DPOPCNT_CAPABILITY -DWITH_TBB \
		-fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`clang++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DBOWTIE_64BIT_INDEX -DNDEBUG -Wall \
		-I /usr/local/include \
		-o bowtie2-align-l bt2_search.cpp \
		ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp qual.cpp pat.cpp sam.cpp read_qseq.cpp aligner_seed_policy.cpp aligner_seed.cpp aligner_seed2.cpp aligner_sw.cpp aligner_sw_driver.cpp aligner_cache.cpp aligner_result.cpp ref_coord.cpp mask.cpp pe.cpp aln_sink.cpp dp_framer.cpp scoring.cpp presets.cpp unique.cpp simple_func.cpp random_util.cpp aligner_bt.cpp sse_util.cpp aligner_swsse.cpp outq.cpp aligner_swsse_loc_i16.cpp aligner_swsse_ee_i16.cpp aligner_swsse_loc_u8.cpp aligner_swsse_ee_u8.cpp aligner_driver.cpp bowtie_main.cpp \
		-lpthread -ltbb -ltbbmalloc_proxy 
In file included from bt2_build.cpp:27:
In file included from ./bt2_idx.h:42:
In file included from ./blockwise_sa.h:24:
In file included from /usr/local/include/tbb/tbb.h:53:
In file included from /usr/local/include/tbb/flow_graph.h:30:
/usr/local/include/tbb/task.h:913:13: error: no matching function for call to object of type 'const VSorting_worker<SString<char> >'
            my_func();
```

**Comment by sjackman** [comment]
Fails to build with `tbb 4.4`. See https://github.com/BenLangmead/bowtie2/issues/34

**Comment by sjackman** [comment]
bowtie2 2.2.9 is released.

**Comment by sjackman** [comment]
Fixes #3440, I hope.

**Comment by sjackman** [comment]
`brew test bowtie2` fail on Travis on Linux:
https://travis-ci.org/Homebrew/homebrew-science/jobs/125082177#L1645
```
/usr/bin/env: python: No such file or directory
```

**Comment by sjackman** [comment]
`tophat` appears to be broken on Mavericks:
```
==> brew linkage --test tophat
==> FAILED
Missing libraries:
  /usr/local/lib/libboost_system-mt.dylib
  /usr/local/lib/libboost_thread-mt.dylib
```
