### PR TITLE
SNAP Aligner 1.0b (update - removes previous binary conflict)

### PR DESCRIPTION
**Pull request by tseemann**
Older versions of this package installed the binary 'snap' which conflicted with the 'snap' package. 

The authors changed the package so the binary is now called 'snap-aligner'.

### CODE REVIEW

**Comment by tseemann** [comment]
Worked with gcc-5.1 on Linux.

```
g++ -O3 -Wno-format -MMD -ISNAPLib -msse   -c -o SNAPLib/AlignmentResult.o SNAPLib/AlignmentResult.cpp
SNAPLib/AlignerContext.cpp:341:34: error: expected ')'
                FormatUIntWithCommas((unsigned _int64)(1000 * stats->totalReads / max(alignTime, (_int64)1)), readsPerSecond, strBufLen),       // Aligntime is in ms
                                               ^
SNAPLib/AlignerContext.cpp:341:24: note: to match this '('
                FormatUIntWithCommas((unsigned _int64)(1000 * stats->totalReads / max(alignTime, (_int64)1)), readsPerSecond, strBufLen),       // Aligntime is in ms
                                     ^
1 error generated.
```

**Comment by jonchang** [comment]
@tseemann replace  `unsigned _int64` with `u_int64_t`

**Comment by ilovezfs** [comment]
This will also need to be reported upstream, which should be prodded to issue a release since this version is designated prerelease and is also quite stale.

**Comment by iMichka** [comment]
I gave this a try, using the latest `1.0beta.23` (they seem to not tag releases anymore, and just wildly bump version numbers).

Build fails with: gcc4.6, gcc4.7, gcc4.8, gcc4.9, gcc5.0, gcc6 and clang.

There seems to be no activity upstream (last commits from Jan. 2016).

I would be in favour of dropping this formula.

**Comment by jonchang** [comment]
I got it to build with a combination of https://github.com/amplab/snap/pull/71 and this patch:

```diff
diff --git a/SNAPLib/SortedDataWriter.cpp b/SNAPLib/SortedDataWriter.cpp
index 85ad336..55d575a 100644
--- a/SNAPLib/SortedDataWriter.cpp
+++ b/SNAPLib/SortedDataWriter.cpp
@@ -335,7 +335,7 @@ SortedDataFilterSupplier::mergeSort()
     }
     for (SortBlockVector::iterator i = blocks.begin(); i != blocks.end(); i++) {
         i->reader = readerSupplier->getDataReader(1, MAX_READ_LENGTH * 8, 0.0,
-            min(1UL << 23, max(1UL << 17, bufferSpace / blocks.size()))); // 128kB to 8MB buffer space per block
+            min(1ULL << 23, max(1ULL << 17, bufferSpace / blocks.size()))); // 128kB to 8MB buffer space per block
         i->reader->init(tempFileName);
         i->reader->reinit(i->start, i->bytes);
     }
```

I don't have access to analytics so I don't know if it's worth it to keep this around. If we decide to keep it I can contact upstream.
