### PR TITLE
hwloc 1.11.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
The latest pocl (0.13) fails to build with our current llvm formula (3.8.1) as well as the prior (3.8.0):
```
/usr/local/Cellar/llvm/3.8.1/bin/clang++ --target=x86_64-apple-macosx10.11.0 -march=skylake -D_CL_DISABLE_HALF -Xclang -ffake-address-space-map -emit-llvm -ffp-contract=off --target=x86_64-apple-darwin15.5.0  -DVML_NO_IOSTREAM -D__OPENCL_VERSION__=200 -Dcl_khr_byte_addressable_store -Dcl_khr_global_int32_base_atomics -Dcl_khr_global_int32_extended_atomics -Dcl_khr_local_int32_base_atomics -Dcl_khr_local_int32_extended_atomics -Dcl_khr_spir -Dcl_khr_int64 -Dcl_khr_fp64 -Dcl_khr_int64_base_atomics -Dcl_khr_int64_extended_atomics -c -o vecmathlib-pocl/acos.cc.bc ../../../lib/kernel/vecmathlib-pocl/acos.cc
In file included from ../../../lib/kernel/vecmathlib-pocl/acos.cc:3:
In file included from ../../../lib/kernel/vecmathlib-pocl/pocl-compat.h:8:
In file included from ../../../lib/kernel/vecmathlib-pocl/../vecmathlib/vecmathlib.h:89:
In file included from ../../../lib/kernel/vecmathlib-pocl/../vecmathlib/vec_pseudo.h:6:
In file included from ../../../lib/kernel/vecmathlib-pocl/../vecmathlib/floatprops.h:6:
../../../lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:44:2: error: 
      "isfinite is not a macro"
#error "isfinite is not a macro"
 ^
../../../lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:47:2: error: "isinf is not a macro"
#error "isinf is not a macro"
 ^
../../../lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:50:2: error: "isnan is not a macro"
#error "isnan is not a macro"
 ^
../../../lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:53:2: error: 
      "isnormal is not a macro"
#error "isnormal is not a macro"
 ^
../../../lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:56:2: error: "signbit is not a macro"
#error "signbit is not a macro"
 ^
5 errors generated.
make[4]: *** [vecmathlib-pocl/acos.cc.bc] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

pocl 0.12 is not compatible with llvm 3.8*, but it does build with our prior major llvm version, which was llvm (3.6.2), however there is one test failure in make check:
```
 16: Kernel functions length, distance, and normalize FAILED (testsuite.at:174)
```

pocl 0.11 also builds with llvm 3.6.2, and make check succeeds, but this may simply be because the test that failed for 0.12 appears to be new.

**Comment by ilovezfs** [comment]
Setting `bottle :disable` for `pocl` since it's known to fail with all available compilers: https://github.com/Homebrew/homebrew-science/pull/4059.

**Comment by sjackman** [comment]
`petsc` bottle needs to be rebuilt for `openmpi`.
```
OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"
#    error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"
     ^
1 error generated.
```

**Comment by sjackman** [comment]
Merged. Thanks, Joe.
