### ISSUE TITLE
openmeeg fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2545]
```
==> Installing openmeeg from homebrew/homebrew-science
==> Downloading https://github.com/openmeeg/openmeeg/archive/release-2.1.tar.gz
==> Downloading from https://codeload.github.com/openmeeg/openmeeg/tar.gz/release-2.1
######################################################################## 100,0%
==> cmake . -DUSE_PROGRESSBAR=ON -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/openmeeg/2.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_V
==> make install
                 ^
1 error generated.
make[2]: *** [libs/MatLib/MatLib/CMakeFiles/OpenMEEGMaths.dir/sparse_matrix.cpp.o] Error 1
make[1]: *** [libs/MatLib/MatLib/CMakeFiles/OpenMEEGMaths.dir/all] Error 2
make: *** [all] Error 2
```

Logs: https://gist.github.com/ca776a3bb0c13f837a5c

**Comment by dpo** [comment]
```
/tmp/openmeeg20150722-36570-1vhitez/openmeeg-release-2.1/libs/MatLib/MatLib/MatLibConfig.h:72:18: fatal error: 'cblas.h' file not found
        #include <cblas.h>
                 ^
```
I don't see a CMake option to specify what BLAS you want to link against. What does `locate cblas.h` say on your system?

**Comment by bfontaine** [comment]
```
$ locate cblas.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/cblas.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/cblas.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/cblas.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/cblas.h
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/cblas.h
/usr/local/Cellar/blis/0.1.6/include/blis/bli_cblas.h
/usr/local/Cellar/blis/0.1.6/include/blis/cblas.h
/usr/local/Cellar/gsl/1.16/include/gsl/gsl_cblas.h
/usr/local/Cellar/openblas/0.2.14_1/include/cblas.h
```

**Comment by dpo** [comment]
That formula really needs updating. The home page has changed.

Does it build if you add `-DCMAKE_C_FLAGS=-framework Accelerate` to the CMake arguments?

**Comment by iMichka** [comment]
Working on this here: #5687

**Comment by iMichka** [comment]
PR merged, 2.4.prerelease is out. This is fixed now.
