### ISSUE TITLE
gnuplot under octave does not build on OSX 10.12.1

### ISSUE THREAD

**Issue by lteneyck** [Homebrew/homebrew-science#4579]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] Checked that a similar issue hasn't already been filed?
- [x ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
homebrew/science/octave 4.2.0-rc2_1
==> Upgrading homebrew/science/octave
==> Installing dependencies for homebrew/science/octave: gnuplot
==> Installing homebrew/science/octave dependency: gnuplot
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.5/
Already downloaded: /Users/lynn/Library/Caches/Homebrew/gnuplot-5.0.5.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gnuplot/5.0.5 
==> make
Last 15 lines from /Users/lynn/Library/Logs/Homebrew/gnuplot/02.make:
    QAnimationGroup(QObject *parent = Q_NULLPTR);
                                      ^
In file included from qtterminal/qt_term.cpp:51:
In file included from /usr/local/Cellar/qt5/5.7.0/include/QtCore/QtCore:6:
/usr/local/Cellar/qt5/5.7.0/include/QtCore/qparallelanimationgroup.h:59:25: error: expected ';' at end of declaration list
    int duration() const Q_DECL_OVERRIDE;
                        ^
                        ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[4]: *** [qtterminal/qt_term.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

#### Brief summary of issue:
This works fine: brew install gnuplot
However, brew install octave (or brew upgrade octave) fails, apparently trying to generate
a gnuplot that supports qt-terminal

brew-gistlogs octave returns Error: No logs
but
brew-gistlogs gnuplot returns a link as shown below.
 

#### Link output by `brew gist-logs <formula>`:
brew gist-logs gnuplot
https://gist.github.com/67f569f3ce45bf5720cb060ba3695028

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b7abd33475b98598b414f9c4ee2e20249855437b
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 375a83c1af8c25290e5d41001e93e335c540e857
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_40
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: 8.1.0.0.1.1476494586
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
It looks like it's trying to build gnuplot with aquaterm and with x11 also, so you probably already had gnuplot installed. Please try uninstalling gnuplot before starting the octave install.

**Comment by ilovezfs** [comment]
As you can see octave and gnuplot should build fine:
```
/usr/local/Cellar/gnuplot/5.0.5: 48 files, 2.6M, built in 1 minute 33 seconds
```
https://bot.brew.sh/job/Homebrew%20Testing/1165/version=any_sierra/consoleFull

**Comment by lteneyck** [comment]
Thank you, once I removed gnuplot, octave installed and runs, and also installs gnuplot.

Aside from the anomaly of the conflict with pre-existing gnuplot installation, the 4.2.0-rc2-1 octave reports itself as being version 3.8.0 and does not start with the gui, as expected for version 4 according to the octave home page. Is this a bug or a feature?
