### ISSUE TITLE
graph-tool failed to build on macOS 10.13 and Xcode 9.0

### ISSUE THREAD

**Issue by moreka** [Homebrew/homebrew-science#6394]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^

#### Brief summary of issue:
While installing graph-tool, it gives errors related to Xcode `<cmath>`. The complete errors can be found in the [gist](https://gist.github.com/b9b25cf156e6dabe60e8aa15ed4fc764). I think there is a problem with clang packed with homebrew.

#### The complete command that you issued:
`brew install graph-tool --without-matplotlib --without-numpy --without-scipy --verbose`

#### Gist with output of `brew doctor`:
[gist](https://gist.github.com/moreka/6229549ea71cc562a2f2222ffc3329a3)

#### Link output by `brew gist-logs <formula>`:
[gist](https://gist.github.com/b9b25cf156e6dabe60e8aa15ed4fc764)

#### Output of `brew config`:
HOMEBREW_VERSION: 1.3.5-14-ge1808bf
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1808bf0e35d522cda4ee4803f13746b604713f5
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6652fbc7c0d201467aab6a515dd14a461dc911c6
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11

### Formula Requests:
graph-tool

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by moreka** [comment]
Same error on Xcode 9.0.1 :-( Pretty annoying...

**Comment by ilovezfs** [comment]
```
ENV.delete("SDKROOT") if DevelopmentTools.clang_build_version >= 900
```
@fxcoudert said it may not be needed as of Xcode 9.1 but I haven't confirmed that personally yet.

**Comment by moreka** [comment]
Worked like a charm! Thanks.
